// ========================================
// Premium Radio Stations — curated, ≥256 kbps, licensed
// ========================================
// Hand-picked stations with reliable high-bitrate streams, ICY metadata (RDS),
// and proper music licensing. Codecs include MP3, AAC, and FLAC (Hi-Res).
// "premium" = bitrate ≥ 256 kbps AND proper content licensing.

const PREMIUM_STATIONS = [
  // ============================================================
  // BBC (UK, PRS-licensed, 320 kbps AAC via HLS — UK-only for 320k)
  // ============================================================
  {
    stationuuid: 'premium-rp-main-320',
    name: 'Radio Paradise — Main Mix',
    url: 'https://stream.radioparadise.com/aac-320',
    url_resolved: 'https://stream.radioparadise.com/aac-320',
    favicon: 'https://radioparadise.com/favicon.ico',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'eclectic,rock,pop,electronic,world music,ambient',
    codec: 'AAC',
    bitrate: 320,
    geo_lat: 39.7392, geo_long: -104.9903,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-rp-mellow-320',
    name: 'Radio Paradise — Mellow Mix',
    url: 'https://stream.radioparadise.com/mellow-320',
    url_resolved: 'https://stream.radioparadise.com/mellow-320',
    favicon: 'https://radioparadise.com/favicon.ico',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'mellow,acoustic,folk,ambient,singer-songwriter',
    codec: 'AAC',
    bitrate: 320,
    geo_lat: 39.7392, geo_long: -104.9903,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-rp-rock-320',
    name: 'Radio Paradise — Rock Mix',
    url: 'https://stream.radioparadise.com/rock-320',
    url_resolved: 'https://stream.radioparadise.com/rock-320',
    favicon: 'https://radioparadise.com/favicon.ico',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'rock,alternative,indie,classic rock,modern rock',
    codec: 'AAC',
    bitrate: 320,
    geo_lat: 39.7392, geo_long: -104.9903,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-rp-global-320',
    name: 'Radio Paradise — Global Mix',
    url: 'https://stream.radioparadise.com/global-320',
    url_resolved: 'https://stream.radioparadise.com/global-320',
    favicon: 'https://radioparadise.com/favicon.ico',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'world music,ethno,global,latin,african,asian',
    codec: 'AAC',
    bitrate: 320,
    geo_lat: 39.7392, geo_long: -104.9903,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-rp-beyond-320',
    name: 'Radio Paradise — Beyond Mix',
    url: 'https://stream.radioparadise.com/beyond-320',
    url_resolved: 'https://stream.radioparadise.com/beyond-320',
    favicon: 'https://radioparadise.com/favicon.ico',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'ambient,electronic,experimental,chillout,downtempo',
    codec: 'AAC',
    bitrate: 320,
    geo_lat: 39.7392, geo_long: -104.9903,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: false,
  },

  // ============================================================
  // Radio Paradise — FLAC (Hi-Res, lossless)
  // ============================================================
  {
    stationuuid: 'premium-rp-main-flac',
    name: 'Radio Paradise — Main Mix (FLAC)',
    url: 'https://stream.radioparadise.com/flac',
    url_resolved: 'https://stream.radioparadise.com/flac',
    favicon: 'https://radioparadise.com/favicon.ico',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'eclectic,rock,pop,electronic,world music,lossless,flac',
    codec: 'FLAC',
    bitrate: 800,
    geo_lat: 39.7392, geo_long: -104.9903,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-rp-rock-flac',
    name: 'Radio Paradise — Rock Mix (FLAC)',
    url: 'https://stream.radioparadise.com/rock-flac',
    url_resolved: 'https://stream.radioparadise.com/rock-flac',
    favicon: 'https://radioparadise.com/favicon.ico',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'rock,alternative,indie,lossless,flac',
    codec: 'FLAC',
    bitrate: 800,
    geo_lat: 39.7392, geo_long: -104.9903,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-rp-beyond-flac',
    name: 'Radio Paradise — Beyond (FLAC MQA)',
    url: 'https://stream.radioparadise.com/beyond-flacm',
    url_resolved: 'https://stream.radioparadise.com/beyond-flacm',
    favicon: 'https://radioparadise.com/favicon.ico',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'ambient,electronic,experimental,lossless,flac,mqa',
    codec: 'FLAC',
    bitrate: 800,
    geo_lat: 39.7392, geo_long: -104.9903,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: true,
  },

  // ============================================================
  // Radio Calico (USA, ASCAP/BMI, Hi-Res 24-bit/48kHz FLAC)
  // ============================================================
  {
    stationuuid: 'premium-radio-calico-flac',
    name: 'Radio Calico (Hi-Res FLAC)',
    url: 'https://stream.radio-calico.com/calico',
    url_resolved: 'https://stream.radio-calico.com/calico',
    favicon: 'https://www.radio-calico.com/wp-content/uploads/2022/11/cropped-radio-calico-32x32.png',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'eclectic,pop,rock,lossless,flac,hi-res,24-bit',
    codec: 'FLAC',
    bitrate: 2304,
    geo_lat: 37.7749, geo_long: -122.4194,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: true,
  },

  // ============================================================
  // SomaFM (USA, licensed commercial-free, 256 kbps MP3)
  // ============================================================
  {
    stationuuid: 'premium-somafm-groovesalad',
    name: 'SomaFM Groove Salad (256k)',
    url: 'https://ice1.somafm.com/groovesalad-256-mp3',
    url_resolved: 'https://ice1.somafm.com/groovesalad-256-mp3',
    favicon: 'https://somafm.com/logos/120/groovesalad120.png',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'ambient,chillout,downtempo,electronic,lounge',
    codec: 'MP3',
    bitrate: 256,
    geo_lat: 37.7749, geo_long: -122.4194,
    clickcount: 99999, votes: 9999,
    license: 'BMI/ASCAP',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-somafm-dronezone',
    name: 'SomaFM Drone Zone (256k)',
    url: 'https://ice1.somafm.com/dronezone-256-mp3',
    url_resolved: 'https://ice1.somafm.com/dronezone-256-mp3',
    favicon: 'https://somafm.com/logos/120/dronezone120.png',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'ambient,space music,dark ambient,drone',
    codec: 'MP3',
    bitrate: 256,
    geo_lat: 37.7749, geo_long: -122.4194,
    clickcount: 99999, votes: 9999,
    license: 'BMI/ASCAP',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-somafm-groovesalad2',
    name: 'SomaFM Groove Salad Classic (256k)',
    url: 'https://ice1.somafm.com/groovesalad2-256-mp3',
    url_resolved: 'https://ice1.somafm.com/groovesalad2-256-mp3',
    favicon: 'https://somafm.com/logos/120/groovesalad2120.jpg',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'ambient,chillout,downtempo,lounge',
    codec: 'MP3',
    bitrate: 256,
    geo_lat: 37.7749, geo_long: -122.4194,
    clickcount: 99999, votes: 9999,
    license: 'BMI/ASCAP',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-somafm-sonicuniverse',
    name: 'SomaFM Sonic Universe (256k)',
    url: 'https://ice1.somafm.com/sonicuniverse-256-mp3',
    url_resolved: 'https://ice1.somafm.com/sonicuniverse-256-mp3',
    favicon: 'https://somafm.com/logos/120/sonicuniverse120.png',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'avant-garde,jazz,electronic,experimental',
    codec: 'MP3',
    bitrate: 256,
    geo_lat: 37.7749, geo_long: -122.4194,
    clickcount: 99999, votes: 9999,
    license: 'BMI/ASCAP',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-somafm-defcon',
    name: 'SomaFM DEF CON Radio (256k)',
    url: 'https://ice1.somafm.com/defcon-256-mp3',
    url_resolved: 'https://ice1.somafm.com/defcon-256-mp3',
    favicon: 'https://somafm.com/logos/120/defcon120.png',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'electronic,downtempo,chillout',
    codec: 'MP3',
    bitrate: 256,
    geo_lat: 37.7749, geo_long: -122.4194,
    clickcount: 99999, votes: 9999,
    license: 'BMI/ASCAP',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-somafm-digitalis',
    name: 'SomaFM Digitalis (256k)',
    url: 'https://ice1.somafm.com/digitalis-256-mp3',
    url_resolved: 'https://ice1.somafm.com/digitalis-256-mp3',
    favicon: 'https://somafm.com/logos/120/digitalis120.png',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'downtempo,electronic,future soul',
    codec: 'MP3',
    bitrate: 256,
    geo_lat: 37.7749, geo_long: -122.4194,
    clickcount: 99999, votes: 9999,
    license: 'BMI/ASCAP',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-somafm-synphaera',
    name: 'SomaFM Synphaera Radio (256k)',
    url: 'https://ice1.somafm.com/synphaera-256-mp3',
    url_resolved: 'https://ice1.somafm.com/synphaera-256-mp3',
    favicon: 'https://somafm.com/logos/120/synphaera120.png',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'ambient,electronic,space music',
    codec: 'MP3',
    bitrate: 256,
    geo_lat: 37.7749, geo_long: -122.4194,
    clickcount: 99999, votes: 9999,
    license: 'BMI/ASCAP',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-somafm-u80s',
    name: 'SomaFM Underground 80s (256k)',
    url: 'https://ice1.somafm.com/u80s-256-mp3',
    url_resolved: 'https://ice1.somafm.com/u80s-256-mp3',
    favicon: 'https://somafm.com/logos/120/u80s120.png',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: '80s,retro,new wave,synthpop,post-punk',
    codec: 'MP3',
    bitrate: 256,
    geo_lat: 37.7749, geo_long: -122.4194,
    clickcount: 99999, votes: 9999,
    license: 'BMI/ASCAP',
    premium: true,
    hiRes: false,
  },

  // ============================================================
  // Incondicionalmente Retro (Chile, SCD-licensed, FLAC)
  // ============================================================
  {
    stationuuid: 'premium-motherearth-main',
    name: 'Mother Earth Radio — Main (FLAC 24/96)',
    url: 'https://stream.motherearthradio.de/listen/motherearth/motherearth.flac-lo',
    url_resolved: 'https://stream.motherearthradio.de/listen/motherearth/motherearth.flac-lo',
    favicon: '',
    country: 'Germany',
    countrycode: 'DE',
    language: 'german,english',
    tags: 'eclectic,rock,indie,ambient,folk,lossless,flac,hi-res,24-bit,vinyl',
    codec: 'FLAC',
    bitrate: 4608,
    geo_lat: 48.1351, geo_long: 11.5820,
    clickcount: 99999, votes: 9999,
    license: 'GVL',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-motherearth-jazz',
    name: 'Mother Earth Radio — Jazz (FLAC 24/96)',
    url: 'https://stream.motherearthradio.de/listen/motherearth_jazz/motherearth.jazz.flac-lo',
    url_resolved: 'https://stream.motherearthradio.de/listen/motherearth_jazz/motherearth.jazz.flac-lo',
    favicon: '',
    country: 'Germany',
    countrycode: 'DE',
    language: 'german,english',
    tags: 'jazz,ecm,free jazz,contemporary jazz,lossless,flac,hi-res',
    codec: 'FLAC',
    bitrate: 4608,
    geo_lat: 48.1351, geo_long: 11.5820,
    clickcount: 99999, votes: 9999,
    license: 'GVL',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-motherearth-klassik',
    name: 'Mother Earth Radio — Klassik (FLAC 24/96)',
    url: 'https://stream.motherearthradio.de/listen/motherearth_klassik/motherearth.klassik.flac-lo',
    url_resolved: 'https://stream.motherearthradio.de/listen/motherearth_klassik/motherearth.klassik.flac-lo',
    favicon: '',
    country: 'Germany',
    countrycode: 'DE',
    language: 'german,english',
    tags: 'classical,historic performances,contemporary,lossless,flac,hi-res',
    codec: 'FLAC',
    bitrate: 4608,
    geo_lat: 48.1351, geo_long: 11.5820,
    clickcount: 99999, votes: 9999,
    license: 'GVL',
    premium: true,
    hiRes: true,
  },

  // ============================================================
  // 60 North Radio (Shetland, PRS-licensed, FLAC CD-quality 1411 kbps)
  // ============================================================
  {
    stationuuid: 'premium-60north-flac',
    name: '60 North Radio (FLAC 1411k)',
    url: 'http://r5.zetcast.net/flac',
    url_resolved: 'http://r5.zetcast.net/flac',
    favicon: 'https://60northradio.com/wp-content/uploads/2022/05/cropped-60-North-Logo-32x32.png',
    country: 'UK',
    countrycode: 'GB',
    language: 'english',
    tags: 'eclectic,folk,rock,world music,shetland,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1411,
    geo_lat: 60.1547, geo_long: -1.1493,
    clickcount: 99999, votes: 9999,
    license: 'PRS',
    premium: true,
    hiRes: true,
  },

  // ============================================================
  // Insanity Radio (UK, PRS-licensed, FLAC)
  // ============================================================
  {
    stationuuid: 'premium-insanity-flac',
    name: 'Insanity Radio (FLAC)',
    url: 'https://stream.cor.insanityradio.com/insanity.flac',
    url_resolved: 'https://stream.cor.insanityradio.com/insanity.flac',
    favicon: 'https://insanityradio.com/favicon.ico',
    country: 'UK',
    countrycode: 'GB',
    language: 'english',
    tags: 'dance,electronic,hip hop,rnb,student radio,lossless,flac',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: 51.2362, geo_long: -0.5704,
    clickcount: 99999, votes: 9999,
    license: 'PRS',
    premium: true,
    hiRes: true,
  },

  // ============================================================
  // Juventus Radio (Hungary, MAHASZ-licensed, FLAC)
  // ============================================================
  {
    stationuuid: 'premium-juventus-flac',
    name: 'Juventus Rádió (FLAC)',
    url: 'https://s2.audiostream.hu/juventus_FLAC',
    url_resolved: 'https://s2.audiostream.hu/juventus_FLAC',
    favicon: 'https://s2.audiostream.hu/favicon.ico',
    country: 'Hungary',
    countrycode: 'HU',
    language: 'hungarian',
    tags: 'pop,charts,hits,hungarian,lossless,flac',
    codec: 'FLAC',
    bitrate: 1000,
    geo_lat: 47.4979, geo_long: 19.0402,
    clickcount: 99999, votes: 9999,
    license: 'MAHASZ',
    premium: true,
    hiRes: true,
  },

  // ============================================================
  // RadioClub80 (Chile, SCD-licensed, FLAC)
  // ============================================================
  {
    stationuuid: 'premium-radioclub80-trance',
    name: 'RadioClub80 — Trance 80s (FLAC)',
    url: 'http://streaminghires.radioclub80.cl:8050/trance80.flac',
    url_resolved: 'http://streaminghires.radioclub80.cl:8050/trance80.flac',
    favicon: 'https://www.radioclub80.cl/wp-content/uploads/2020/05/cropped-radioclub80-icon-32x32.png',
    country: 'Chile',
    countrycode: 'CL',
    language: 'spanish',
    tags: 'trance,80s,electronic,synth,lossless,flac',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: -33.4489, geo_long: -70.6693,
    clickcount: 99999, votes: 9999,
    license: 'SCD',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-radioclub80-live',
    name: 'RadioClub80 — Live Mix (FLAC)',
    url: 'http://stream.radioclub80.cl:9040/live.flac',
    url_resolved: 'http://stream.radioclub80.cl:9040/live.flac',
    favicon: 'https://www.radioclub80.cl/wp-content/uploads/2020/05/cropped-radioclub80-icon-32x32.png',
    country: 'Chile',
    countrycode: 'CL',
    language: 'spanish',
    tags: '80s,90s,pop,spanish,lossless,flac',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: -33.4489, geo_long: -70.6693,
    clickcount: 99999, votes: 9999,
    license: 'SCD',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-radioclub80-espanol',
    name: 'RadioClub80 — Español 80s (FLAC)',
    url: 'https://stream.radioclub80.cl:8012/espanol80.flac',
    url_resolved: 'http://stream.radioclub80.cl:8010/espanol80.flac',
    favicon: 'https://www.radioclub80.cl/wp-content/uploads/2020/05/cropped-radioclub80-icon-32x32.png',
    country: 'Chile',
    countrycode: 'CL',
    language: 'spanish',
    tags: '80s,spanish,pop,latin,lossless,flac',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: -33.4489, geo_long: -70.6693,
    clickcount: 99999, votes: 9999,
    license: 'SCD',
    premium: true,
    hiRes: true,
  },

  // ============================================================
  // Danubius Radio (Hungary, MAHASZ-licensed, 320 kbps MP3)
  // ============================================================
  {
    stationuuid: 'premium-danubius-hifi',
    name: 'Danubius Rádió HiFi (320k MP3)',
    url: 'https://danubiusradio.hu/live_HiFi.mp3',
    url_resolved: 'http://stream.danubiusradio.hu/danubius_HiFi',
    favicon: 'https://danubiusradio.hu/favicon.ico',
    country: 'Hungary',
    countrycode: 'HU',
    language: 'hungarian',
    tags: 'pop,top 40,hits,hungarian,charts',
    codec: 'MP3',
    bitrate: 320,
    geo_lat: 47.4979, geo_long: 19.0402,
    clickcount: 99999, votes: 9999,
    license: 'MAHASZ',
    premium: true,
    hiRes: false,
  },

  // ============================================================
  // CD-Quality FLAC stations (verified working, ~1000 kbps)
  // ============================================================
  {
    stationuuid: 'premium-bigbang-radio',
    name: 'Big Bang Radio (FLAC)',
    url: 'https://audio-edge-cmc51.fra.h.radiomast.io/2b410ada-8653-40aa-a654-3e8954cf4a4d',
    url_resolved: 'https://audio-edge-cmc51.fra.h.radiomast.io/2b410ada-8653-40aa-a654-3e8954cf4a4d',
    favicon: '',
    country: 'France',
    countrycode: 'FR',
    language: 'french',
    tags: 'eclectic,pop,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: 48.8566, geo_long: 2.3522,
    clickcount: 99999, votes: 9999,
    license: 'SACEM',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-djam-radio',
    name: 'Djam Radio (FLAC)',
    url: 'https://stream10.xdevel.com/audio15s976748-2280/stream/icecast.audio',
    url_resolved: 'https://stream10.xdevel.com/audio15s976748-2280/stream/icecast.audio',
    favicon: '',
    country: 'France',
    countrycode: 'FR',
    language: 'french',
    tags: 'eclectic,pop,alternative,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: 48.8566, geo_long: 2.3522,
    clickcount: 99999, votes: 9999,
    license: 'SACEM',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-lebon-mix',
    name: 'Le Bon Mix (FLAC)',
    url: 'https://stream10.xdevel.com/audio17s976748-2218/stream/icecast.audio',
    url_resolved: 'https://stream10.xdevel.com/audio17s976748-2218/stream/icecast.audio',
    favicon: '',
    country: 'France',
    countrycode: 'FR',
    language: 'french',
    tags: 'eclectic,funk,jazz,disco,house,soul,world,rock,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: 48.8566, geo_long: 2.3522,
    clickcount: 99999, votes: 9999,
    license: 'SACEM',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-sanctuary-80s',
    name: 'Sanctuary Radio — 80s Alternative (FLAC)',
    url: 'https://stream.sanctuaryradio.com/retrochannel_uhq',
    url_resolved: 'https://stream.sanctuaryradio.com/retrochannel_uhq',
    favicon: '',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: '80s,alternative,post-punk,new wave,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: 40.7128, geo_long: -74.0060,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-sanctuary-club',
    name: 'Sanctuary Radio — Club Mix (FLAC)',
    url: 'https://stream.sanctuaryradio.com/clubmix_channel_uhq',
    url_resolved: 'https://stream.sanctuaryradio.com/clubmix_channel_uhq',
    favicon: '',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'dance,club,house,electronic,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: 40.7128, geo_long: -74.0060,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-sanctuary-dark',
    name: 'Sanctuary Radio — Dark Electro (FLAC)',
    url: 'https://stream.sanctuaryradio.com/mainchannel_uhq',
    url_resolved: 'https://stream.sanctuaryradio.com/mainchannel_uhq',
    favicon: '',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'electro,dark,industrial,ebm,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: 40.7128, geo_long: -74.0060,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-roxy-radio',
    name: 'Roxy Rádió (FLAC)',
    url: 'https://s2.audiostream.hu/roxy_FLAC',
    url_resolved: 'https://s2.audiostream.hu/roxy_FLAC',
    favicon: 'https://s2.audiostream.hu/favicon.ico',
    country: 'Hungary',
    countrycode: 'HU',
    language: 'hungarian',
    tags: 'pop,hits,hungarian,charts,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1000,
    geo_lat: 47.4979, geo_long: 19.0402,
    clickcount: 99999, votes: 9999,
    license: 'MAHASZ',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-bdpst-rock',
    name: 'BDPST Rock Radio (FLAC)',
    url: 'https://s2.audiostream.hu/bdpstrock_FLAC',
    url_resolved: 'https://s2.audiostream.hu/bdpstrock_FLAC',
    favicon: 'https://s2.audiostream.hu/favicon.ico',
    country: 'Hungary',
    countrycode: 'HU',
    language: 'hungarian',
    tags: 'rock,classic rock,modern rock,hungarian,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1000,
    geo_lat: 47.4979, geo_long: 19.0402,
    clickcount: 99999, votes: 9999,
    license: 'MAHASZ',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-radio-90fm-valencia',
    name: 'Radio 90FM Valencia (FLAC)',
    url: 'https://azura.radio90.fm/listen/radio90/stream',
    url_resolved: 'https://azura.radio90.fm/listen/radio90/stream',
    favicon: '',
    country: 'Spain',
    countrycode: 'ES',
    language: 'spanish',
    tags: 'dance,techno,electronic,spanish,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: 39.4699, geo_long: -0.3763,
    clickcount: 99999, votes: 9999,
    license: 'SGAE',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-easyradio',
    name: 'EasyRadio Bulgaria (FLAC)',
    url: 'http://live.easyradio.bg/flac',
    url_resolved: 'http://live.easyradio.bg/flac',
    favicon: '',
    country: 'Bulgaria',
    countrycode: 'BG',
    language: 'bulgarian',
    tags: 'easy listening,pop,lounge,instrumental,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: 42.6977, geo_long: 23.3219,
    clickcount: 99999, votes: 9999,
    license: 'PROPHON',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-sing-sing',
    name: 'Radio Sing Sing (FLAC)',
    url: 'http://stream.sing-sing-bis.org:8000/singsingFlac',
    url_resolved: 'http://stream.sing-sing-bis.org:8000/singsingFlac',
    favicon: '',
    country: 'Croatia',
    countrycode: 'HR',
    language: 'croatian,english',
    tags: 'jazz,soul,funk,world,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: 45.8150, geo_long: 15.9819,
    clickcount: 99999, votes: 9999,
    license: 'HDS',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-radio-random',
    name: 'Radio Random (FLAC)',
    url: 'http://radiorandom.org:8000/WBJM-FLAC',
    url_resolved: 'http://radiorandom.org:8000/WBJM-FLAC',
    favicon: '',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'eclectic,community,freeform,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: 40.7128, geo_long: -74.0060,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-radiosega',
    name: 'RadioSEGA (FLAC)',
    url: 'https://icecast.radiosega.net/rs-flac.ogg',
    url_resolved: 'https://icecast.radiosega.net/rs-flac.ogg',
    favicon: 'https://radiosega.net/favicon.ico',
    country: 'UK',
    countrycode: 'GB',
    language: 'english',
    tags: 'retro,gaming,video game music,soundtrack,chiptune,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: 51.5074, geo_long: -0.1278,
    clickcount: 99999, votes: 9999,
    license: 'PRS',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-intense-radio',
    name: 'Intense Radio (FLAC)',
    url: 'https://secure.live-streams.nl/flac.flac',
    url_resolved: 'https://secure.live-streams.nl/flac.flac',
    favicon: '',
    country: 'Netherlands',
    countrycode: 'NL',
    language: 'english',
    tags: 'electronic,dance,house,trance,hardstyle,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: 52.1326, geo_long: 5.2913,
    clickcount: 99999, votes: 9999,
    license: 'BUMA/STEMRA',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-sveriges-radio-p2',
    name: 'Sveriges Radio P2 (FLAC)',
    url: 'https://live1.sr.se/p2-flac',
    url_resolved: 'https://live1.sr.se/p2-flac',
    favicon: 'https://www.sverigesradio.se/favicon.ico',
    country: 'Sweden',
    countrycode: 'SE',
    language: 'swedish',
    tags: 'classical,jazz,world music,folk,swedish,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1100,
    geo_lat: 59.3293, geo_long: 18.0686,
    clickcount: 99999, votes: 9999,
    license: 'STIM',
    premium: true,
    hiRes: true,
  },
  // Czech Radio (ČRo) — all FLAC CD-quality, OSA-licensed
  {
    stationuuid: 'premium-riverside-radio',
    name: 'Riverside Radio (FLAC)',
    url: 'https://stream.and-stuff.nl:8443/riverside',
    url_resolved: 'https://stream.and-stuff.nl:8443/riverside',
    favicon: 'https://www.riversideradio.nl/favicon.ico',
    country: 'The Netherlands',
    countrycode: 'NL',
    language: 'dutch,english',
    tags: 'rock,classic rock,progressive rock,album rock,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 2000,
    geo_lat: 52.0907, geo_long: 5.1214,
    clickcount: 99999, votes: 9999,
    license: 'BUMA/STEMRA',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-distorsion-fm-flac',
    name: 'Distorsión FM — Rock & Jazz (FLAC)',
    url: 'https://radioemisoras.cl/distorsion.flac',
    url_resolved: 'https://radioemisoras.cl/distorsion.flac',
    favicon: 'https://distorsion.fm/logo.png',
    country: 'Chile',
    countrycode: 'CL',
    language: 'spanish,english',
    tags: 'rock,classic rock,metal,jazz,lossless,flac,cd-quality,chile',
    codec: 'FLAC',
    bitrate: 1200,
    geo_lat: -33.4489, geo_long: -70.6693,
    clickcount: 99999, votes: 9999,
    license: 'SCD',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-radioclub80-rock',
    name: 'RadioClub80 Rock — Classic Rock (FLAC 24/96)',
    url: 'http://stream.radioclub80.cl:9040/live.flac',
    url_resolved: 'http://stream.radioclub80.cl:9040/live.flac',
    favicon: 'https://radioclub80.cl/wp-content/uploads/2022/03/cropped-logo-1-32x32.png',
    country: 'Chile',
    countrycode: 'CL',
    language: 'spanish,english',
    tags: 'rock,classic rock,hard rock,80s,90s,lossless,flac,24-bit,hi-res,cd-quality',
    codec: 'FLAC',
    bitrate: 3072,
    geo_lat: -33.4489, geo_long: -70.6693,
    clickcount: 99999, votes: 9999,
    license: 'SCD',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-radio-bluesflac',
    name: 'Super Stereo 5 — Rock & Blues (FLAC)',
    url: 'https://audio-edge-cmc51.fra.h.radiomast.io/radioblues-flac',
    url_resolved: 'https://audio-edge-cmc51.fra.h.radiomast.io/radioblues-flac',
    favicon: 'https://www.superstereo24bit.com/favicon.ico',
    country: 'Chile',
    countrycode: 'CL',
    language: 'spanish,english',
    tags: 'rock,blues,classic rock,album rock,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1500,
    geo_lat: -33.4489, geo_long: -70.6693,
    clickcount: 99999, votes: 9999,
    license: 'SCD',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-highfi-dream',
    name: 'HighFi Dream — Indie & Synthpop (FLAC)',
    url: 'https://cdn06-us-east.radio.cloud/80ba63862a97bd69c593cc7a2ccaab1c_hq',
    url_resolved: 'https://cdn06-us-east.radio.cloud/80ba63862a97bd69c593cc7a2ccaab1c_hq',
    favicon: 'https://highfidream.com/favicon.ico',
    country: 'The United States Of America',
    countrycode: 'US',
    language: 'english',
    tags: 'indie,alternative,shoegaze,dream pop,synthpop,new wave,trip-hop,neo-soul,electronic,psychedelic,post-punk,lossless,flac',
    codec: 'FLAC',
    bitrate: 1200,
    geo_lat: 40.7128, geo_long: -74.0060,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: true,
  },

  // ============================================================
  // 80s / 90s / RETRO (FLAC + MP3 320)
  // ============================================================
  {
    stationuuid: 'premium-futura-fm',
    name: 'Futura FM — 80s & Retro (FLAC)',
    url: 'https://futura.fm/stream.ogg',
    url_resolved: 'https://futura.fm/stream.ogg',
    favicon: 'https://futura.fm/favicon.ico',
    country: 'Italy',
    countrycode: 'IT',
    language: 'italian,english',
    tags: '80s,retro,classic hits,pop rock,disco,itpop,lossless,flac',
    codec: 'FLAC',
    bitrate: 1500,
    geo_lat: 45.4642, geo_long: 9.1900,
    clickcount: 99999, votes: 9999,
    license: 'SIAE',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-frequence3-gold',
    name: 'Fréquence 3 Gold — 80s & 90s (FLAC)',
    url: 'https://frequence3.net-radio.fr/frequence3gold.flac',
    url_resolved: 'https://frequence3.net-radio.fr/frequence3gold.flac',
    favicon: 'https://api2.frequence3.net/static/img/stations/horizontal/frequence3gold.png',
    country: 'France',
    countrycode: 'FR',
    language: 'french,english',
    tags: '80s,90s,oldies,classic hits,pop,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1536,
    geo_lat: 48.8566, geo_long: 2.3522,
    clickcount: 99999, votes: 9999,
    license: 'SACEM',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-memories-radio',
    name: 'Memories Radio — 80s & 90s',
    url: 'https://stream1.468.gr/8108/stream',
    url_resolved: 'https://stream1.468.gr/8108/stream',
    favicon: 'http://resources.live24.gr/resources/images/stations/2a470594-bbfa-4064-b503-620ee4d57ae0.png',
    country: 'Greece',
    countrycode: 'GR',
    language: 'greek,english',
    tags: '80s,90s,pop,classic hits,greek pop,retro',
    codec: 'MP3',
    bitrate: 320,
    geo_lat: 37.9838, geo_long: 23.7275,
    clickcount: 99999, votes: 9999,
    license: 'AEPI',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-oxygen-90s',
    name: 'Oxygen The 90s Hits',
    url: 'https://oxygenmusic.hu:8443/oxygenthe90shits',
    url_resolved: 'https://oxygenmusic.hu:8443/oxygenthe90shits',
    favicon: 'https://oxygenmusic.hu/logo192.png',
    country: 'Hungary',
    countrycode: 'HU',
    language: 'english',
    tags: '90s,classic hits,pop,dance,eurodance,hungarian',
    codec: 'MP3',
    bitrate: 320,
    geo_lat: 47.4979, geo_long: 19.0402,
    clickcount: 99999, votes: 9999,
    license: 'MAHASZ',
    premium: true,
    hiRes: false,
  },

  // ============================================================
  // SOUNDTRACK / FILM SCORE / MUSICAL / ANIME
  // ============================================================
  {
    stationuuid: 'premium-shadowfr69',
    name: 'shadowfr69 Radio — Anime OST & VGM',
    url: 'https://radio.shadowfr69.eu/mp3',
    url_resolved: 'https://radio.shadowfr69.eu/mp3',
    favicon: 'https://shadowfr69.eu/favicon.ico',
    country: 'France',
    countrycode: 'FR',
    language: 'japanese,english',
    tags: 'anime,anime soundtracks,ost,jpop,vgm,video game,game music,japanese',
    codec: 'MP3',
    bitrate: 256,
    geo_lat: 48.8566, geo_long: 2.3522,
    clickcount: 99999, votes: 9999,
    license: 'SACEM',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-oxygen-spencer',
    name: 'Oxygen Spencer-Hill — Italo & Soundtrack',
    url: 'https://oxygenmusic.hu:8443/oxygenspencerhillzenek',
    url_resolved: 'https://oxygenmusic.hu:8443/oxygenspencerhillzenek',
    favicon: 'https://oxygenmusic.hu/logo192.png',
    country: 'Hungary',
    countrycode: 'HU',
    language: 'english,italian',
    tags: 'italo,pop dance,disco,soundtrack,easy listening,hungarian',
    codec: 'MP3',
    bitrate: 320,
    geo_lat: 47.4979, geo_long: 19.0402,
    clickcount: 99999, votes: 9999,
    license: 'MAHASZ',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-box-office-radio',
    name: 'Box Office Radio — Broadway & West End',
    url: 'https://s2.citrus3.com:8400/stream',
    url_resolved: 'https://s2.citrus3.com:8400/stream',
    favicon: 'https://boxofficeradio.co.uk/upload/design/63236b1e497e25.64641412.png',
    country: 'The United Kingdom Of Great Britain And Northern Ireland',
    countrycode: 'GB',
    language: 'english',
    tags: 'broadway,musical,musicals,showtunes,soundtrack,film music,stage,theater,theatre,west end',
    codec: 'MP3',
    bitrate: 256,
    geo_lat: 51.5074, geo_long: -0.1278,
    clickcount: 99999, votes: 9999,
    license: 'PRS',
    premium: true,
    hiRes: false,
  },

  // ============================================================
  // WORLD / JAZZ / SOUL / FUNK (FLAC)
  // ============================================================
  {
    stationuuid: 'premium-frequence3-world',
    name: 'Fréquence 3 World — Soul & Jazz (FLAC)',
    url: 'https://frequence3.net-radio.fr/frequence3world.flac',
    url_resolved: 'https://frequence3.net-radio.fr/frequence3world.flac',
    favicon: 'https://www.frequence3.com/wp-content/themes/frequence3/img/logo-frequence3-WORLD.svg',
    country: 'France',
    countrycode: 'FR',
    language: 'french,english,portuguese,spanish',
    tags: 'world,soul,rnb,funk,acid jazz,trip-hop,latin jazz,dub,afrobeat,lossless,flac',
    codec: 'FLAC',
    bitrate: 1536,
    geo_lat: 48.8566, geo_long: 2.3522,
    clickcount: 99999, votes: 9999,
    license: 'SACEM',
    premium: true,
    hiRes: true,
  },

  // ============================================================
  // DANCE / HOUSE (FLAC)
  // ============================================================
  {
    stationuuid: 'premium-frequence3-dance',
    name: 'Fréquence 3 Dance — House (FLAC)',
    url: 'https://frequence3.net-radio.fr/frequence3dance.flac',
    url_resolved: 'https://frequence3.net-radio.fr/frequence3dance.flac',
    favicon: 'https://api2.frequence3.net/static/img/stations/horizontal/frequence3dance.png',
    country: 'France',
    countrycode: 'FR',
    language: 'french,english',
    tags: 'dance,house,electronic,club,lossless,flac,cd-quality',
    codec: 'FLAC',
    bitrate: 1536,
    geo_lat: 48.8566, geo_long: 2.3522,
    clickcount: 99999, votes: 9999,
    license: 'SACEM',
    premium: true,
    hiRes: true,
  },
  {
    stationuuid: 'premium-kexp-flac',
    name: 'KEXP 90.3 FM (FLAC)',
    url: 'https://kexp.streamguys1.com/kexp160.m3u8',
    url_resolved: 'https://kexp.streamguys1.com/kexp160.m3u8',
    favicon: 'https://kexp.org/static/assets/img/kexp-logo-white.png',
    country: 'USA',
    countrycode: 'US',
    language: 'english',
    tags: 'alternative,indie,rock,eclectic,live',
    codec: 'AAC',
    bitrate: 160,
    geo_lat: 47.6062, geo_long: -122.3321,
    clickcount: 99999, votes: 9999,
    license: 'ASCAP/BMI',
    premium: true,
    hiRes: false,
  },
  {
    stationuuid: 'premium-sector-space-flac',
    name: 'Sector Radio — Space (FLAC)',
    url: 'http://89.223.45.5:8000/space-flac',
    url_resolved: 'http://89.223.45.5:8000/space-flac',
    favicon: 'https://sectorradio.com/space/logo.png',
    country: 'Russia',
    countrycode: 'RU',
    language: 'english',
    tags: 'ambient,space,electronic,lossless,flac',
    codec: 'FLAC',
    bitrate: 1000,
    geo_lat: 55.7558, geo_long: 37.6173,
    clickcount: 99999, votes: 9999,
    license: 'PRO',
    premium: true,
    hiRes: true,
  }
];

export function getPremiumStations() {
  return PREMIUM_STATIONS.map(s => {
    const genre = s.tags ? extractGenreForPremium(s.tags, s.name) : 'misc';
    return {
      ...s,
      genre,
      genreColor: getGenreColorLocal(genre),
      health: 100,
    };
  });
}

function extractGenreForPremium(tags, name) {
  const tagStr = (tags || '').toLowerCase();
  const nameStr = (name || '').toLowerCase();
  const combined = tagStr + ' ' + nameStr;

  const genreMap = [
    ['soundtrack', ['soundtrack', 'soundtracks', 'ost ', 'ost,', 'score', 'anime', 'game music', 'film scores', 'musical theatre', 'broadway']],
    ['afrobeats', ['afrobeats', 'afrobeat', 'amapiano', 'afro house', 'afro pop']],
    ['reggae', ['reggae', 'dancehall', 'dub', 'ska']],
    ['hip hop', ['hip hop', 'hiphop', 'hip-hop', 'rap', 'trap', 'drill', 'grime']],
    ['rnb', ['rnb', 'r&b', 'neo soul']],
    ['latin', ['latin', 'salsa', 'reggaeton', 'bachata', 'merengue', 'cumbia']],
    ['country', ['country', 'bluegrass', 'americana']],
    ['classical', ['classical', 'klassik', 'opera', 'symphony', 'orchestra', 'baroque', 'chamber music']],
    ['jazz', ['jazz', 'swing', 'bebop', 'smooth jazz', 'nu jazz']],
    ['blues', ['blues', 'delta blues', 'chicago blues']],
    ['gospel', ['gospel', 'worship', 'christian', 'spiritual']],
    ['ethno', ['ethno', 'ethnic', 'celtic', 'polka', 'gypsy', 'world music']],
    ['news', ['news', 'talk', 'discussion', 'documentary', 'culture', 'current affairs', 'sports']],
    ['lounge', ['lounge', 'chillout', 'chill', 'downtempo']],
    ['trance', ['trance', 'vocal trance', 'progressive trance', 'psytrance']],
    ['techno', ['techno', 'minimal techno']],
    ['house', ['house', 'deep house', 'tech house']],
    ['edm', ['edm', 'big room', 'festival edm']],
    ['electronic', ['electronic', 'electronica', 'idm', 'synthwave', 'retrowave', 'electro', 'garage', 'experimental']],
    ['metal', ['metal', 'heavy metal', 'death metal', 'black metal', 'thrash']],
    ['punk', ['punk', 'punk rock', 'post-punk', 'hardcore']],
    ['indie', ['indie', 'indie rock', 'indie pop', 'alternative rock', 'alt rock', 'alternative']],
    ['rock', ['rock', 'classic rock', 'hard rock', 'progressive rock', 'rock & roll', 'new wave']],
    ['pop', ['k-pop', 'j-pop', 'europop', 'latin pop', 'dance pop', 'electropop', 'synthpop', 'teen pop', 'britpop', 'power pop', 'indie pop', 'pop music', 'pop rock', 'singer-songwriter']],
    ['charts', ['top 40', 'top40', 'billboard', 'hot 100', 'official charts']],
    ['hits', ['hits', 'greatest hits', 'best hits', 'hit music', 'all hits', 'top hits']],
    ['disco', ['disco', 'discofox', 'nu disco', 'italo disco']],
    ['dance', ['dance', 'dance pop', 'club', 'party']],
    ['soul', ['soul', 'motown', 'northern soul']],
    ['funk', ['funk', 'funky', 'p-funk']],
    ['ambient', ['ambient', 'new age', 'space music', 'drone', 'dark ambient']],
    ['retro', ['retro', 'oldies', 'classic hits', 'golden oldies', 'mellow', 'acoustic', 'folk']],
  ];

  const scores = new Map();
  for (let i = 0; i < genreMap.length; i++) {
    const [genre, keywords] = genreMap[i];
    let score = 0;
    for (const kw of keywords) {
      if (kw.length < 2) continue;
      if (combined.includes(kw)) {
        score += kw.length;
      }
    }
    if (score > 0) scores.set(genre, { score, order: i });
  }

  let best = null;
  for (const [genre, info] of scores) {
    if (!best || info.score > best.score || (info.score === best.score && info.order < best.order)) {
      best = { genre, ...info };
    }
  }

  if (best) return best.genre;
  const tagList = tagStr.split(',').map(t => t.trim()).filter(Boolean);
  if (tagList.length > 0) return tagList[0];
  return 'misc';
}

function getGenreColorLocal(genre) {
  const g = (genre || '').toLowerCase();
  if (g.includes('rock')) return '#ef4444';
  if (g.includes('pop')) return '#3b82f6';
  if (g.includes('jazz') || g.includes('blues')) return '#f59e0b';
  if (g.includes('classical')) return '#8b5cf6';
  if (g.includes('electronic') || g.includes('techno') || g.includes('house')) return '#06b6d4';
  if (g.includes('hip hop') || g.includes('rap') || g.includes('rnb')) return '#ec4899';
  if (g.includes('country') || g.includes('folk')) return '#10b981';
  if (g.includes('news') || g.includes('talk')) return '#6b7280';
  if (g.includes('retro') || g.includes('oldies') || g.includes('80') || g.includes('90')) return '#f97316';
  return '#3b82f6';
}
